name: Call API every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          AUTH_HEADER="Basic $(echo -n 'qwerty@buildersspace9999Revant:asdfghjkwertyuicvbnmrevantsdfghjk2345678fghjrpeavaarnttkh' | base64)"
          RESPONSE=$(curl -X GET -s -w "\nHTTP_STATUS:%{http_code}" \
            -H "Authorization: $AUTH_HEADER" \
            "https://builderspace.onrender.com/api/void-request-for-active-state/")
          echo "Response: $RESPONSE"
