name: Call API every 15 minutes

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to API
        run: |
          RESPONSE=$(curl -X GET -s -w "\nHTTP_STATUS:%{http_code}" "https://builderspace.onrender.com/api/void-request-for-active-state/")
          echo "Response: $RESPONSE"
