name: Trigger Void Request Every 10 Minutes

on:
  schedule:
    - cron: '*/8 * * * *' # Runs every 10 minutes

jobs:
  call-void-request-api:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Void Request API
        run: |
          curl -X GET "https://buildersspace.tech/api/triggerVoidRequest"