name: Call API every 15 minutes

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to API
        env:
          API_USER: ${{ secrets.API_BASIC_AUTH_USERNAME }}
          API_PASS: ${{ secrets.API_BASIC_AUTH_PASSWORD }}
        run: |
          AUTH_HEADER="Basic $(echo -n ${API_USER}:${API_PASS} | base64)"
          RESPONSE=$(curl -X GET -s -w "\nHTTP_STATUS:%{http_code}" \
            -H "Authorization: $AUTH_HEADER" \
            "https://builderspace.onrender.com/api/void-request-for-active-state/")
          echo "Response: $RESPONSE"
