name: Trigger Void Request Every 10 Minutes

on:
  schedule:
    - cron: '*/8 * * * *' # Runs every 8 minutes
  workflow_dispatch:

jobs:
  call-void-request-api:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Void Request API
        run: |
          curl -X GET "https://builderspace.onrender.com/api/void-request-for-active-state/" \
            -H "Authorization: Basic $(echo -n 'qwerty@buildersspace9999Revant:asdfghjkwertyuicvbnmrevantsdfghjk2345678fghjrpeavaarnttkh' | base64 -w 0)" \
            -H "Content-Type: application/json"